[package]
build = './common/build/build.rs'
description = 'Overlay protocol library'
edition = '2021'
name = 'overlay'
version = '0.6.105'

[workspace]


[dependencies]
async-trait = '0.1'
base64 = '0.13'
failure = '0.1'
hex = '0.4'
log = '0.4'
num-traits = '0.2'
rand = '0.7'
sha2 = '0.9'
adnl = { features = [ 'node' ], git = 'https://github.com/tonlabs/ton-labs-adnl.git', tag = '0.7.111' }
ever-crypto = { git = 'https://github.com/tonlabs/ever-labs-crypto.git', tag = '0.1.73' }
lockfree = { git = 'https://github.com/tonlabs/lockfree.git' }
rldp = { git = 'https://github.com/tonlabs/ton-labs-rldp.git', tag = '0.7.107' }
tokio = { features = [ 'rt-multi-thread' ], version = '1.5' }
ton_api = { git = 'https://github.com/tonlabs/ton-labs-tl.git', package = 'ton_api', tag = '0.2.160' }
ton_block = { git = 'https://github.com/tonlabs/ton-labs-block.git', tag = '1.9.10' }
ton_types = { git = 'https://github.com/tonlabs/ton-labs-types.git', tag = '1.12.4' }

[features]
dump = [ 'adnl/dump' ]
telemetry = [ 'adnl/telemetry', 'rldp/telemetry' ]

